# Generated by Django 2.2.3 on 2022-11-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autocarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100, unique=True)),
                ('lotacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Carreira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Carreira')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=9)),
                ('data_nascimento', models.DateField()),
                ('num_bi', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Paragem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PontoRegisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('paragem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Paragem')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAutocarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCarreira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaidaAutocarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('autocarro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Autocarro')),
                ('bilhete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Bilhete')),
                ('cartao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Cartao')),
                ('ponto_registo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.PontoRegisto')),
            ],
        ),
        migrations.CreateModel(
            name='Percurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_percurso', models.CharField(choices=[('ida', 'ida'), ('Volta', 'Volta')], max_length=10)),
                ('carreira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Carreira')),
                ('paragem', models.ManyToManyField(to='mainApp.Paragem')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaAutocarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('autocarro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Autocarro')),
                ('bilhete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Bilhete')),
                ('cartao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Cartao')),
                ('ponto_registo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.PontoRegisto')),
            ],
        ),
        migrations.AddField(
            model_name='cartao',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Cliente'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='tipo_cartao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.TipoCartao'),
        ),
        migrations.AddField(
            model_name='carreira',
            name='ponto_fim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponto_fim', to='mainApp.Paragem'),
        ),
        migrations.AddField(
            model_name='carreira',
            name='ponto_inicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponto_inicio', to='mainApp.Paragem'),
        ),
        migrations.AddField(
            model_name='carreira',
            name='tipo_carreira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.TipoCarreira'),
        ),
        migrations.AddField(
            model_name='bilhete',
            name='carreira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Carreira'),
        ),
        migrations.CreateModel(
            name='Avaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Avaria', 'Avaria'), ('Substituicao', 'Substituicao')], max_length=20)),
                ('local', models.CharField(max_length=100)),
                ('autocarro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Autocarro')),
            ],
        ),
        migrations.CreateModel(
            name='AutocarroCarreira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autocarro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Autocarro')),
                ('carreira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Carreira')),
            ],
        ),
        migrations.AddField(
            model_name='autocarro',
            name='tipo_autocarro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.TipoAutocarro'),
        ),
    ]
